#!/bin/bash
set -e

PROGNAME=$(basename $0)

die() {
    echo "$PROGNAME: $*" >&2
    exit 1
}

usage() {
    if [ "$*" != "" ] ; then
        echo "Error: $*"
    fi

    cat << EOF
Usage: $PROGNAME [OPTION ...] [foo] [bar]

Options:
-h, --help                       display this usage message and exit
-c, --clean                      remove all files generated by this script
-p, --picturedir [PICTURE DIR]   path to directory containing training images
-r, --percentage [  0 - 100  ]   how many percentage of the data should train
                                 contain. ( default is 70% -> 15% for test set
                                 and 15% for validation set )
EOF
    exit 1
}

if [ -z "$1" ]
  then
    usage "No argument supplied"
fi

data="./../data/data.txt"
train="./../data/train.txt"
testvalid="./../data/tmp_testvalid.txt"
test="./../data/test.txt"
validation="./../data/validation.txt"
pic_dir=""
procent=0.70
while [ $# -gt 0 ] ; do
    case "$1" in
    -h|--help)
        usage
        ;;
    -c|--clean)
        if [ -f $data ] ; then
            rm $data
            echo "Removed $data"
        fi
        if [ -f $test ] ; then
            rm $test
            echo "Removed $test"
        fi
        if [ -f $train ] ; then
            rm $train
            echo "Removed $train"
        fi
        exit 0
        ;;
    -p|--picturedir)
        if [ ! -d $2 ] || [ -z $2 ]; then
          die "Directory '$2' not found!"
        fi
        pic_dir="$2"
        shift
        ;;
    -r|--percentage)
        procent=`bc <<<"scale=2; $2 / 100"`
        shift
        ;;
    -*)
        usage "Unknown option '$1'"
        ;;
    *)
        usage "Invalid parameter was provided: '$1'"
        ;;
    esac
    shift
done

ls $pic_dir | sed -e 's/\..*$//' > $data

num_lines=`find $pic_dir -maxdepth 1 | wc -l`
num_lines=$((num_lines-1))
limit=$(expr $num_lines*$procent | bc | awk '{print int($1+0.5)}')

find $pic_dir -maxdepth 1 | head -n "$limit" > $train
sed -i '1d' $train

limit=$((limit+1))
find $pic_dir -maxdepth 1 | tail -n +"$limit" > $testvalid

lines=`wc -l $testvalid | cut -f1 -d' '`
splitpoint=`expr $lines / 2`

cat $testvalid | head -n "$splitpoint" > $test
cat $testvalid | tail -n +"$splitpoint" > $validation

rm $testvalid &> /dev/null

echo "Generated $data"
echo "Generated $train"
echo "Generated $test"
echo "Generated $validation"
